version: '3.1'

services: 

  # Create a localstack container for AWS services
  localstack:
    container_name: aws-localstack
    image: localstack/localstack:latest
    environment:
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
      - EDGE_PORT=4566
      - SERVICES=s3,logs,lambda,iam,cloudwatch
      - LOCALSTACK_TMP_DIR=/tmp/localstack-custom
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "/tmp/localstack-custom:/tmp/localstack-custom"
      - "/var/run/docker.sock:/var/run/docker.sock"
  
  # Create a PostGIS container for spatial data
  postgis:
    image: postgis/postgis:latest
    container_name: trip_postgis
    restart: always
    environment:
      POSTGRES_USER: tripuser
      POSTGRES_PASSWORD: trippass
      POSTGRES_DB: tripdb
    ports:
      - "5432:5432"
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d